"""Owner-facing descriptions for the known-variant catalogue.

One description per CONDITION (trait), applied to every variant of that trait
by enrich_catalog.py. Matching: exact normalized trait first, then the first
matching prefix rule. Written for a general audience: what the condition is,
how it is inherited where established, and what a result means — hedged, never
alarmist. Sources: the primary veterinary genetics literature behind each OMIA
phene; descriptions are condition-level background, not clinical advice.
"""

# ── family rules: (prefix, description) — first match wins ──────────────────
PREFIX = [
    ("Progressive Retinal Atrophy", "A group of inherited eye conditions in which the light-sensing cells of the retina gradually degenerate, usually leading to night blindness first and eventual vision loss. Most forms are recessive: dogs need two copies to be affected, and vision loss develops over years."),
    ("Golden Retriever Progressive Retinal Atrophy", "A Golden Retriever form of progressive retinal atrophy — gradual degeneration of the retina's light-sensing cells leading to progressive vision loss. Recessive: two copies are needed for the condition to appear."),
    ("Neuronal Ceroid Lipofuscinosis", "A family of inherited storage diseases in which waste material builds up in nerve cells, causing progressive neurological decline (loss of coordination, vision problems, behavioral change) typically starting in young adulthood. Recessive — carriers are healthy."),
    ("Mucopolysaccharidosis", "An inherited storage disease in which the body cannot fully break down certain complex sugars, which accumulate and affect bones, joints, eyes and organs. Recessive — two copies are needed."),
    ("Glycogen Storage Disease", "An inherited inability to store or release glycogen (the body's sugar reserve) properly, typically causing low blood sugar, exercise intolerance and organ enlargement. Recessive."),
    ("Glycogen storage disease", "An inherited inability to store or release glycogen (the body's sugar reserve) properly, typically causing low blood sugar, exercise intolerance and organ enlargement. Recessive."),
    ("Von Willebrand Disease", "The most common inherited bleeding disorder of dogs: a shortage or defect of von Willebrand factor, a protein needed for blood clotting. Affected dogs may bruise easily or bleed longer after injury or surgery; severity varies by type. Mostly recessive, and worth mentioning to your vet before any surgery."),
    ("Cystinuria", "An inherited kidney transport defect in which the amino acid cystine leaks into urine and can form bladder or kidney stones, more often in males. Management focuses on diet and urinary monitoring."),
    ("Coat Length", "A coat-trait variant, not a disease: this change in the FGF5 gene region is one of several that produce a long coat when a dog carries two long-coat copies in total."),
    ("Brown color", "A coat-color variant, not a disease: TYRP1 'brown' alleles turn black pigment to brown/liver (including nose and paw pads) when a dog carries two brown alleles in any combination."),
    ("Color Dilution", "A coat-color variant, not a disease on its own: two dilution copies lighten black pigment to blue/grey and brown to lilac. In some breeds dilute coats can be prone to a patchy hair loss called color-dilution alopecia."),
    ("Recessive Red", "A coat-color variant, not a disease: with two recessive-red copies at MC1R, the coat grows only yellow-to-red pigment regardless of most other color genes."),
    ("Curly Coat", "A coat-texture variant, not a disease: KRT71 curl alleles produce a wavy to curly coat, as in Poodles and doodle mixes."),
    ("Ichthyosis", "An inherited skin condition in which the outer skin layer does not form normally, causing flaking, scaling and a rough or darkened skin surface. Usually recessive; severity varies widely and management is topical."),
    ("Cerebellar Ataxia", "An inherited degeneration of the cerebellum, the balance-and-coordination center of the brain, causing a wobbly gait that typically worsens over time. Recessive — carriers are unaffected."),
    ("Cerebellar", "An inherited condition of the cerebellum, the brain's balance-and-coordination center, producing an unsteady, uncoordinated gait. Recessive forms are typical — carriers are healthy."),
    ("Spinocerebellar", "An inherited degeneration affecting the cerebellum and spinal pathways, causing progressive incoordination, sometimes with muscle twitching or seizures. Recessive."),
    ("Spongy Degeneration", "A severe inherited brain disease of puppies in which brain tissue develops a sponge-like change, causing early ataxia and neurological decline. Recessive — carriers are healthy."),
    ("Muscular Dystrophy", "An inherited muscle-wasting disease in which muscle fibers progressively weaken and are replaced by scar tissue, causing weakness and exercise intolerance from a young age."),
    ("Limb-girdle muscular dystrophy", "An inherited muscle disease causing progressive weakness of the shoulder and hip muscles. Recessive."),
    ("Muscular Hypertrophy", "The 'bully whippet' myostatin variant: one copy is associated with a more muscular build; two copies produce heavy, double-muscled dogs. A body-build trait rather than an illness."),
    ("Factor ", "An inherited deficiency of one of the blood-clotting factors, causing prolonged bleeding after injury or surgery — severity ranges from mild to serious depending on the factor and variant. Worth telling your vet before any procedure."),
    ("Hereditary Nephropathy", "An inherited kidney disease in which the kidney's filtering membranes are structurally weak, leading to protein loss in urine and progressive kidney failure, often at a young age in affected dogs."),
    ("Familial Nephropathy", "An inherited kidney disease in which the kidney's filtering membranes are structurally weak, leading to protein loss in urine and progressive kidney failure, often at a young age in affected dogs."),
    ("Oculocutaneous Albinism", "An inherited pigment deficiency affecting coat, skin and eyes, giving very pale coloring and light-sensitive eyes. A pigmentation trait, recessive."),
    ("Primary Open Angle Glaucoma", "An inherited form of glaucoma in which pressure builds inside the eye, which is painful and can damage vision; some forms also loosen the lens. Regular eye-pressure checks help catch it early in at-risk dogs."),
    ("Elliptocytosis", "An inherited red-blood-cell shape abnormality that can shorten red-cell life and cause mild anemia."),
    ("Severe Combined Immunodeficiency", "A severe inherited failure of the immune system: affected puppies cannot fight infections and rarely survive without extreme measures. Carriers are completely healthy."),
    ("Deafness and vestibular", "An inherited syndrome combining deafness with balance problems, appearing in puppies. Recessive."),
    ("Amelogenesis Imperfecta", "An inherited enamel defect: teeth form with thin or pitted enamel, look discolored, and wear or chip easily. Managed with dental care."),
    ("Ectodermal Dysplasia", "An inherited developmental condition of skin, hair and teeth — affected dogs can have sparse hair, missing teeth, or fragile skin depending on the form."),
    ("Epidermolysis", "An inherited skin-fragility disease: the skin layers separate with minor friction, causing blisters and sores. Severity varies by form."),
    ("Epidermal bullosa", "An inherited skin-fragility disease: the skin layers separate with minor friction, causing blisters and sores."),
    ("Canine Multifocal Retinopathy", "An inherited retinal condition producing localized areas of retinal detachment visible on eye exams; vision is usually only mildly affected and lesions can partially resolve. Recessive."),
    ("Laryngeal", "An inherited condition affecting the nerves of the voice box (and often other long nerves), causing noisy breathing, voice change and exercise intolerance, sometimes with generalized polyneuropathy."),
    ("Juvenile-Onset Polyneuropathy", "An inherited nerve disease appearing in young dogs, causing progressive hind-limb weakness, exercise intolerance and sometimes noisy breathing from voice-box involvement."),
    ("Hereditary Ataxia", "An inherited loss of coordination caused by degeneration in the brain's movement circuits, typically appearing in puppies or young dogs and progressing over time."),
    ("Neuroaxonal Dystrophy", "An inherited degeneration of nerve fibers in the brain and spinal cord causing progressive incoordination and neurological decline, usually starting young. Recessive."),
    ("Fetal-Onset Neonatal Neuroaxonal", "A severe inherited nerve-fiber degeneration beginning before birth, causing stillbirth or severe neurological signs in newborn puppies. Recessive — carriers are healthy."),
    ("Oculoskeletal dysplasia", "An inherited syndrome combining dwarfism with serious eye abnormalities including retinal detachment. Recessive."),
    ("Skeletal Dysplasia", "An inherited mild dwarfism: affected dogs have shortened legs relative to their body without other health problems. Recessive."),
    ("Osteochondrodysplasia", "An inherited skeletal growth disorder causing disproportionate dwarfism, with short limbs and possible joint changes."),
    ("Osteogenesis Imperfecta", "'Brittle bone disease' — an inherited collagen defect making bones fragile and prone to fracture, with possible dental and joint involvement, from puppyhood."),
    ("Intestinal cobalamin", "An inherited inability to absorb vitamin B12 from food, causing poor growth, lethargy and anemia in young dogs — very treatable with B12 supplementation once recognized."),
    ("Intestinal Cobalamin", "An inherited inability to absorb vitamin B12 from food, causing poor growth, lethargy and anemia in young dogs — very treatable with B12 supplementation once recognized."),
    ("Imerslund", "An inherited inability to absorb vitamin B12 from food, causing poor growth, lethargy and anemia in young dogs — very treatable with B12 supplementation once recognized."),
    ("Copper Toxicosis", "An inherited defect of copper handling in the liver: copper accumulates over years and can cause chronic liver damage. Manageable with diet and medication when identified."),
    ("Hyperekplexia", "An inherited 'startle disease': affected puppies stiffen dramatically in response to noise or handling. Recessive."),
    ("Startle Disease", "An inherited 'startle disease': affected puppies stiffen dramatically in response to noise or handling. Recessive."),
]

# ── exact entries ───────────────────────────────────────────────────────────
EXACT = {
    "2,8-Dihydroxyadenine Urolithiasis (2,8-DHA Urolithiasis)": "An inherited enzyme deficiency that lets an insoluble compound (2,8-DHA) form stones in the urinary tract. Recessive; managed with diet and medication.",
    "Achromatopsia, cone degeneration": "An inherited loss of the retina's cone cells, causing day blindness and complete color-vision loss while night vision is preserved. Recessive.",
    "Acute Respiratory Distress Syndrome": "An inherited predisposition to sudden, severe lung inflammation in young dogs. Recessive and rare.",
    "Acyl-CoA dehydrogenase medium chain deficiency": "An inherited defect in burning medium-chain fats for energy, which can cause low energy and metabolic crises, especially when fasting.",
    "Afibrinogenaemia": "An inherited absence of fibrinogen, a key clotting protein, causing a serious bleeding tendency.",
    "Alexander Disease": "A rare inherited brain disease in which a structural protein misbehaves in support cells, causing progressive neurological decline in young dogs.",
    "Ancient Red (eA)": "A coat-color variant, not a disease: an ancient MC1R allele producing red/yellow coats in some breeds and village-dog lineages.",
    "Bandera's Neonatal Ataxia": "A severe inherited coordination disorder evident as soon as puppies try to walk; affected pups cannot stand or walk purposefully. Recessive.",
    "Benign Familial Juvenile Epilepsy, Remitting Focal Epilepsy": "An inherited epilepsy of puppies that typically begins and resolves within the first months of life; most dogs outgrow it fully.",
    "Beta Mannosidosis": "A rare inherited storage disease in which a sugar-processing enzyme is missing, causing progressive neurological disease. Recessive.",
    "Canine Leukocyte Adhesion Deficiency Type I (CLAD I)": "A severe inherited immune defect: white blood cells cannot reach infection sites, causing recurrent, life-threatening infections in puppies. Recessive.",
    "Canine Leukocyte Adhesion Deficiency Type III (CLAD III)": "A severe inherited immune defect combining recurrent infections with a bleeding tendency. Recessive.",
    "Canine Scott Syndrome": "A rare inherited platelet defect causing prolonged bleeding after injury or surgery despite normal platelet counts.",
    "Cardiac Laminopathy (CLAM)": "A severe inherited heart-muscle disease of young dogs caused by a structural-protein defect, leading to heart failure or sudden death.",
    "Cardiomyopathy and Juvenile Mortality": "An inherited heart-muscle disease causing death in puppies or young dogs. Recessive — carriers are healthy.",
    "Centronuclear Myopathy (CNM)": "An inherited muscle disease in which muscle fibers develop abnormally, causing weakness, poor exercise tolerance and difficulty holding the head up, from a few months of age.",
    "Centronuclear Myopathy 1": "An inherited muscle disease in which muscle fibers develop abnormally, causing weakness and poor exercise tolerance from a young age.",
    "Chondrodystrophy": "A body-shape variant: an extra FGF4 gene copy produces the short-legged build of many breeds. It is also associated with premature disc aging.",
    "Chondrodystrophy and Intervertebral Disc Disease (CDDY/IVDD, Type I IVDD)": "The FGF4-chr12 variant behind short-legged builds also causes discs to age prematurely, raising the risk of painful disc herniation (IVDD). One of the most consequential structural variants in dogs — keeping affected dogs lean and limiting spine-jarring activity helps.",
    "Ciliary dyskinesia": "An inherited defect of the microscopic 'brushes' that clear airways, causing chronic nasal discharge, cough and recurrent respiratory infections from early life.",
    "Cleft Lip and/or Cleft Palate, with syndactyly": "An inherited developmental defect of the lip/palate (with fused toes in some pups), evident at birth.",
    "Cleft Palate, brachygnathism": "An inherited developmental defect in which the palate does not close and the jaw is short; evident at birth.",
    "Cocoa color": "A coat-color variant, not a disease: the HPS3 'cocoa' allele of French Bulldogs darkens brown pigment distinctly from the TYRP1 browns.",
    "Cone Degeneration": "An inherited loss of retinal cone cells causing day blindness and absent color vision, with night vision preserved. Recessive.",
    "Day Blindness, Cone Degeneration, Achromatopsia": "An inherited loss of retinal cone cells causing day blindness and absent color vision, with night vision preserved. Recessive.",
    "Congenital Dyshormonogenic hypothyroidism with Goiter": "An inherited inability to make thyroid hormone, causing stunted growth and an enlarged thyroid in puppies; treatable with thyroid supplementation when caught early.",
    "Congenital Hypothyroidism": "An inherited thyroid hormone deficiency from birth, causing disproportionate dwarfism and lethargy; treatable with hormone replacement when identified early.",
    "Congenital Eye Malformations": "Inherited structural eye abnormalities present from birth, ranging from small eyes to internal malformations affecting vision.",
    "Congenital Macrothrombocytopenia": "A benign inherited platelet trait: platelets are fewer but larger, and lab counts look low without a true bleeding problem — worth knowing so it is not mistaken for disease.",
    "Congenital Muscular Dystrophy": "An inherited muscle disease evident from puppyhood, causing weakness and poor growth.",
    "Congenital Myasthenic Syndrome": "An inherited fault at the nerve-muscle junction, causing weakness that worsens with exercise in puppies. Recessive.",
    "Congenital insensitivity to pain": "An inherited nerve defect in which affected dogs cannot feel pain normally, typically leading to self-injury of paws; appears in puppies. Recessive.",
    "Craniomandibular Osteopathy": "An inherited bone overgrowth of the jaw and skull in growing puppies, painful during flare-ups but typically self-limiting as growth ends.",
    "Cyclic Neutropenia": "'Grey Collie syndrome' — an inherited disorder in which infection-fighting cells drop in ~2-week cycles, causing recurring fevers and infections. Recessive and serious.",
    "Cystic renal dysplasia and hepatic fibrosis": "An inherited developmental disorder of kidneys and liver causing cysts and scarring in young dogs.",
    "Darier Disease": "An inherited skin disorder causing wart-like, crusted skin lesions.",
    "Deafness": "An inherited form of deafness. In dogs, deafness is also commonly linked to white-pigment patterns; a BAER hearing test gives a definitive answer for an individual dog.",
    "Degenerative Myelopathy": "A late-onset inherited spinal-cord degeneration (the canine analog of ALS): painless, progressive hind-limb weakness typically beginning after age 8. The SOD1 variant is a strong risk factor rather than a certainty — many two-copy dogs never develop signs. Recessive-with-incomplete-penetrance.",
    "Dental Hypomineralization": "An inherited enamel-mineralization defect making teeth wear quickly and appear discolored; managed with dental care.",
    "Dilated Cardiomyopathy": "An inherited heart-muscle weakness in which the heart enlarges and pumps poorly, potentially leading to heart failure; onset is typically in adulthood and regular cardiac checks help at-risk dogs.",
    "Disproportionate Dwarfism": "An inherited skeletal dysplasia producing short limbs relative to body size.",
    "Dyserythropoietic Anemia and Myopathy Syndrome (DAMS)": "A rare inherited syndrome combining abnormal red-cell production with muscle disease.",
    "Dystonia-ataxia syndrome": "An inherited movement disorder combining abnormal muscle contractions with incoordination.",
    "Ehlers-Danlos Syndrome": "An inherited connective-tissue defect: skin is stretchy, fragile and tears easily, and joints can be loose. Managed by protecting the skin from trauma.",
    "Epilepsy, mitochondrial dysfunction and neurodegeneration": "An inherited energy-metabolism defect of nerve cells causing seizures and progressive neurological decline.",
    "Episodic Falling Syndrome": "An inherited exercise-triggered muscle stiffness of Cavalier King Charles Spaniels: episodes of rigid limbs and collapse with normal consciousness, often manageable with medication.",
    "Exercise induced metabolic myopathy": "An inherited defect in muscle energy metabolism causing weakness or collapse during intense exercise.",
    "Exercise-Induced Collapse": "The DNM1 variant: affected dogs (two copies) can develop wobbly hind limbs and collapse after 5-15 minutes of intense excitement or exercise, then recover fully. Managed by moderating high-intensity play. Carriers are unaffected.",
    "Exfoliative cutaneous lupus erythematosus": "An inherited autoimmune skin disease causing scaling and hair loss, typically starting in young adulthood.",
    "Eye Color": "A pigmentation trait, not a disease: variants near ALX4 are associated with blue eyes, notably in Huskies.",
    "Familial adenomatous polyposis": "An inherited predisposition to numerous intestinal polyps that can progress to cancer; affected dogs benefit from GI surveillance.",
    "Fanconi Syndrome": "An inherited kidney-tubule defect in which nutrients are lost into urine, causing excessive drinking, weight loss and metabolic imbalance; manageable with supplementation protocols. Seen classically in Basenjis.",
    "Focal Non-Epidermolytic Palmoplantar Keratoderma, Pachyonychia Congenita": "An inherited thickening of paw-pad skin and nails causing discomfort on hard ground.",
    "GM1 Gangliosidosis": "A severe inherited storage disease of nerve cells causing progressive neurological decline in puppies. Recessive — carriers are healthy.",
    "GM2 Gangliosidosis": "A severe inherited storage disease of nerve cells (the canine analog of Tay-Sachs) causing progressive neurological decline in puppies. Recessive.",
    "Glanzmann's Thrombasthenia Type I": "An inherited platelet-function defect: platelets cannot clump properly, causing gum bleeds, nosebleeds and prolonged bleeding after procedures. Recessive.",
    "Globoid Cell Leukodystrophy, Krabbe disease": "A severe inherited disease of nerve insulation (myelin), causing progressive weakness and neurological decline in young dogs. Recessive.",
    "Grizzle (EG)": "A coat-pattern variant, not a disease: the MC1R 'grizzle/domino' allele produces the shaded facial patterns of Salukis and Afghan Hounds.",
    "Growth hormone deficiency dwarfism": "An inherited pituitary growth-hormone deficiency causing proportionate dwarfism and coat problems; seen classically in German Shepherd lines.",
    "Hair Ridge": "A coat trait, not a disease: the duplication behind the Rhodesian Ridgeback's ridge. Two copies increase the risk of a skin condition called dermoid sinus.",
    "Harlequin (H/h)": "A coat-pattern modifier of merle in Great Danes: with merle, one copy produces the white-with-black-patches harlequin pattern. Two copies are not viable, so harlequins are always carriers.",
    "Hereditary Footpad Hyperkeratosis": "An inherited overgrowth of paw-pad horn causing thick, cracked pads that can be painful on hard surfaces; managed with softening care.",
    "Hereditary Nasal Parakeratosis, HNPK": "An inherited nose-surface disorder: the nose leather becomes dry, crusted and discolored. Cosmetic-to-uncomfortable; managed with topical care. Recessive, best known in Labradors.",
    "Hereditary Sensory Autonomic Neuropathy, Acral Mutilation Syndrome (AMS)": "An inherited loss of pain sensation in the paws leading affected young dogs to self-injure; a serious welfare condition. Recessive.",
    "Hereditary Vitamin D-Resistant Rickets": "An inherited inability to respond to vitamin D, causing soft, deformed bones in puppies despite normal diet.",
    "Hidden Patterning (KB/ky)": "A coat-color switch, not a disease: the dominant KB allele makes the coat solid eumelanin, hiding pattern genes; ky/ky dogs show their agouti pattern.",
    "Hyperuricosuria and Hyperuricemia, Urolithiasis (HUU)": "An inherited defect of uric-acid handling (universal in Dalmatians) causing urate bladder/kidney stones, especially in males. Managed with diet and hydration. Recessive.",
    "Hypocatalasia, Acatalasemia": "An inherited deficiency of the enzyme catalase, occasionally associated with mouth ulcers; usually mild.",
    "Hypomyelinating Polyneuropathy": "An inherited deficiency of nerve insulation causing weakness and tremor in puppies.",
    "Hypophosphatasia": "An inherited enzyme deficiency affecting bone mineralization, causing soft bones and dental problems in puppies.",
    "Hyposegmentation of granulocytes": "A benign inherited change in white-blood-cell appearance (Pelger-Huët-like); usually no health impact but can confuse lab work.",
    "Inflammatory Myopathy": "An inherited immune-mediated muscle inflammation causing progressive weakness and muscle loss in young dogs.",
    "Inflammatory Pulmonary Disease": "An inherited predisposition to chronic airway inflammation and recurrent respiratory infections in puppies.",
    "Inherited Myopathy": "An inherited muscle disease causing weakness and exercise intolerance from a young age.",
    "Intestinal Lipid Malabsorpotion": "An inherited difficulty absorbing dietary fats, causing poor weight gain and digestive signs.",
    "Juvenile Cataract": "An inherited clouding of the lens appearing in young dogs; can progress to impair vision, and is surgically treatable.",
    "Juvenile Myoclonic Epilepsy": "An inherited epilepsy of young dogs featuring brief muscle-jerk seizures, often light-sensitive; typically medication-responsive.",
    "L-2-Hydroxyglutaricaciduria (L2HGA)": "An inherited metabolic disorder in which an acid accumulates in the brain, causing seizures, wobbliness and behavioral change from adolescence. Recessive, best known in Staffordshire Bull Terriers.",
    "Lagotto Storage Disease": "An inherited storage disease of Lagotto Romagnolos causing progressive incoordination and eye-movement abnormalities in young dogs. Recessive.",
    "Leukodystrophy": "An inherited disorder of the brain's white matter causing progressive neurological decline in young dogs.",
    "Leukoencephalomyelopathy": "An inherited degeneration of white matter in the brain and spinal cord causing progressive weakness and incoordination in young dogs. Recessive.",
    "Ligneous Membranitis": "A rare inherited plasminogen deficiency causing woody, inflamed membranes of the eyes, mouth and gums.",
    "Lissencephaly and cerebellar hypoplasia": "A severe inherited brain-development disorder ('smooth brain') causing seizures and profound neurological deficits in puppies.",
    "Long QT Syndrome": "An inherited heart-rhythm disorder that can cause fainting or sudden death; identified dogs benefit from cardiology guidance and avoiding certain drugs.",
    "Lundehund Syndrome": "The Norwegian Lundehund's inherited intestinal disease: protein is lost through an inflamed gut, causing weight loss and effusions; lifelong dietary management.",
    "Lung development disease": "An inherited lung-development defect causing respiratory distress in newborn puppies.",
    "MDR1 Drug Sensitivity": "The famous multidrug-sensitivity variant: dogs with the MDR1 deletion cannot pump certain drugs out of the brain, making common medications (ivermectin, loperamide, some sedatives and chemotherapy drugs) potentially dangerous at normal doses. One copy warrants caution; two copies require strict avoidance — always share this result with your vet.",
    "Malignant Hyperthermia": "An inherited reaction to certain anesthetic gases: affected dogs can develop runaway muscle rigidity and body temperature under anesthesia. Dominant — one copy matters, and your vet/anesthetist should know before any procedure.",
    "May-Hegglin Anomaly": "A benign inherited platelet/white-cell anomaly that can make platelet counts look low without a true bleeding problem.",
    "Methemoglobinaemia": "An inherited enzyme deficiency in which a portion of hemoglobin is locked in a form that cannot carry oxygen, causing bluish gums and reduced stamina; usually mild.",
    "Microphthalmia": "An inherited developmental defect producing abnormally small eyes with variable vision impairment, present from birth.",
    "Mitochondrial fission encephalopathy": "A severe inherited defect of mitochondrial dynamics causing early-onset neurological disease.",
    "Musladin-Lueke Syndrome (MLS)": "The Beagle connective-tissue syndrome: tight, thick skin, stiff joints and a characteristic tip-toe gait. Recessive; affected dogs often live full lives with accommodations.",
    "Myeloencephalopathy, progressive and degenerative": "An inherited progressive degeneration of the spinal cord and brain causing worsening weakness and incoordination.",
    "Myeloperoxidase Deficiency": "An inherited deficiency of a white-blood-cell enzyme, mildly reducing bacterial killing; usually without obvious illness.",
    "Myotonia Congenita": "An inherited muscle-relaxation defect: muscles stiffen with initial movement ('warm-up' stiffness), giving a stiff bunny-hop gait. Recessive; dogs adapt well.",
    "Myotubular Myopathy 1, X-linked Myotubular Myopathy (XL-MTM)": "A severe X-linked muscle disease of male puppies causing rapidly progressive weakness. Females are typically healthy carriers.",
    "Narcolepsy": "An inherited sleep-switch defect: affected dogs collapse suddenly into sleep during excitement (classically at mealtimes). Not painful and not progressive. Recessive.",
    "Neonatal Encephalopathy with Seizures (NEWS)": "A severe inherited brain disorder of newborn puppies causing weakness, tremors and seizures. Recessive, seen in Standard Poodle lines.",
    "Osteochondromatosis": "An inherited tendency to form multiple bony outgrowths during growth, which can press on nearby structures; usually stabilizes at maturity.",
    "Paroxysmal Dyskinesia": "An inherited episodic movement disorder: bouts of cramping or abnormal movements with normal consciousness, often triggered by excitement; not epilepsy.",
    "Periodic Fever Syndrome": "The Shar-Pei autoinflammatory syndrome: recurrent unexplained fevers and swollen hocks, related to the same biology as the breed's skin folds; managed medically.",
    "Persistent Mullerian Duct Syndrome (PMDS)": "An inherited condition of male dogs that retain internal female duct structures; can cause cryptorchidism and is otherwise usually silent.",
    "Pituitary Dwarfism": "An inherited pituitary hormone deficiency causing proportionate dwarfism and coat abnormalities; treatable when identified young.",
    "Polycystic Kidney Disease": "An inherited condition in which fluid-filled cysts form in the kidneys and can progressively reduce kidney function; monitored with imaging and kidney values.",
    "Polyneuropathy, ocular abnormalities, and neuronal vacuolation": "An inherited syndrome combining nerve degeneration with eye abnormalities in young dogs.",
    "Prekallikrein Deficiency": "An inherited clotting-cascade quirk that prolongs one lab clotting test but rarely causes real-world bleeding; good for your vet to know before surgery.",
    "Primary Ciliary Dyskinesia": "An inherited defect of the airway's microscopic cilia causing chronic nasal discharge, cough and recurrent airway infections from early life.",
    "Primary Hyperoxaluria": "An inherited metabolic defect causing oxalate crystal deposition in kidneys, leading to early kidney failure. Recessive.",
    "Primary Lens Luxation": "An inherited weakness of the fibers holding the eye's lens: the lens can slip out of place in middle age, which is an emergency for vision. Knowing risk in advance enables monitoring. Semi-dominant with two-copy dogs at high risk.",
    "Progressive Neuronal Abiotrophy, Canine Multiple System Degeneration (CMSD)": "An inherited multi-system brain degeneration causing progressive movement difficulties in young dogs.",
    "Protein Losing Nephropathy": "An inherited kidney-filter weakness that leaks protein into urine and can progress to kidney disease; monitored with urine and blood checks. Best known in soft-coated Wheaten Terriers.",
    "Pyruvate Dehydrogenase Deficiency": "An inherited energy-metabolism defect causing exercise intolerance and metabolic acidosis.",
    "Pyruvate Kinase Deficiency": "An inherited red-blood-cell enzyme deficiency causing chronic anemia and, over time, bone and liver changes. Recessive.",
    "Recessive Black (a)": "A coat-color variant, not a disease: two copies of the recessive ASIP 'a' allele make a solid black coat, common in shepherd breeds.",
    "Red Pigment Intensity (I/i)": "A coat-color modifier, not a disease: intensity variants dial red/yellow pigment from deep red to cream.",
    "Renal Cystadenocarcinoma and Nodular Dermatofibrosis (RCND)": "An inherited cancer-predisposition syndrome of German Shepherds combining kidney tumors with characteristic skin nodules; dominant, so one copy matters — surveillance imaging is recommended.",
    "Rod-Cone Dystrophy": "An inherited degeneration of both rod and cone photoreceptors leading to progressive vision loss. Recessive.",
    "Sensory Neuropathy": "An inherited degeneration of sensory nerves causing loss of sensation, incoordination and self-injury in young dogs.",
    "Shaking Puppy Syndrome, X-linked Generalized Tremor Syndrome": "An X-linked myelin deficiency causing dramatic whole-body tremors in male puppies; carrier females are usually normal.",
    "Shedding (T)": "A coat trait, not a disease: MC5R 'shedding' variants influence how heavily a dog sheds, interacting with furnishings.",
    "Spinal Dysraphism": "An inherited spinal-cord malformation causing a characteristic crouched, hopping gait; present from puppyhood and non-progressive.",
    "Spondylocostal Dysostosis": "An inherited malformation of vertebrae and ribs ('comma defect'), causing a shortened, kinked spine; severity varies.",
    "Stargardt Disease": "An inherited macular degeneration causing gradual central-vision loss in adult dogs.",
    "Subacute Necrotizing Encephalomyelopathy": "The dog analog of Leigh syndrome: an inherited energy-metabolism defect of the brain causing progressive neurological decline in young dogs. Recessive.",
    "Succinic Semialdehyde Dehydrogenase deficiency": "An inherited neurotransmitter-metabolism defect causing developmental delay, incoordination and seizures.",
    "Taillessness": "A tail-length trait, not a disease: the T-box natural bobtail variant. One copy shortens the tail; two copies are not viable, so bobtails are always carriers.",
    "Thrombopathia": "An inherited platelet-function defect causing easy bruising, gum bleeds and prolonged bleeding after procedures. Tell your vet before surgery.",
    "Ventricular arrhythmias and sudden death": "An inherited heart-rhythm disorder that can cause fainting or sudden death in young dogs; cardiology screening is advised for at-risk dogs.",
    "Verrucous Epidermal Keratinocytic Nevi": "An inherited localized skin overgrowth producing wart-like, pigmented plaques.",
    "Vitamin D Deficiency rickets, type 1A": "An inherited inability to activate vitamin D, causing soft bones in puppies; treatable with the active vitamin form.",
    "Early retinal degeneration": "An inherited early-onset retinal degeneration causing vision loss in young dogs. Recessive.",
    "Early-onset adult deafness": "An inherited progressive hearing loss beginning in early adulthood; a BAER hearing test tracks it definitively.",
    "Early-onset progressive polyneuropathy": "An inherited degeneration of peripheral nerves causing progressive weakness and incoordination beginning in young dogs.",
    "Xanthinuria type II": "An inherited defect of purine metabolism causing xanthine bladder/kidney stones; managed with diet and hydration.",
}

def describe(trait):
    t = " ".join(str(trait or "").split()).strip().rstrip(",")
    if not t:
        return None
    if t in EXACT:
        return EXACT[t]
    for prefix, d in PREFIX:
        if t.startswith(prefix) or prefix in t:
            return d
    return None
